### ISSUE TITLE
ToDo for 3.0

### ISSUE THREAD

**Issue by tknerr** [tknerr/bills-kitchen#101]
Todo's for the 3.0 final release:

 * [ ] make rake clean work (`apm uninstall atom-beautify`)
 * [ ] vagrant docker remote host patch: fix multi-vm portforwarding issue
 * [ ] cache baseboxes for faster builds (#93)
 * [ ] add proxy on/off script
 * [ ] conditionally b2d download if iso not present
